// Widths
localparam
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_EVT_LTC         = 49,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_START_ADDR      = 11,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_STOP_ADDR       = 11,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_TRIG_SRC        = 2,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_CNST_RUN        = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_PRE_CONF        = 5,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_SYNC_RDY        = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_BSUM            = 19,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_BSUM_LEN_SEL    = 3,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_BSUM_VALID      = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_LOCAL_COINC     = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_PARTIAL_WFM     = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_CONTINUED_WFM   = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_CHANNEL_IDX     = 5;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_EVT_LTC         = 0,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_START_ADDR      = 49,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_STOP_ADDR       = 60,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_TRIG_SRC        = 71,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_CNST_RUN        = 73,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_PRE_CONF        = 74,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_SYNC_RDY        = 79,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_BSUM            = 80,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_LEN_SEL    = 99,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_VALID      = 102,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_LOCAL_COINC     = 103,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_PARTIAL_WFM     = 104,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_CONTINUED_WFM   = 105,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_CHANNEL_IDX     = 106;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_EVT_LTC         = 48,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_START_ADDR      = 59,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_STOP_ADDR       = 70,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_TRIG_SRC        = 72,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_CNST_RUN        = 73,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_PRE_CONF        = 78,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_SYNC_RDY        = 79,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_BSUM            = 98,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_LEN_SEL    = 101,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_VALID      = 102,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_LOCAL_COINC     = 103,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_PARTIAL_WFM     = 104,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_CONTINUED_WFM   = 105,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_CHANNEL_IDX     = 110;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_SCDB_HDR_BUNDLE_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_SCDB_HDR_BUNDLE = 111;
