// Widths
localparam
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_EVT_LTC         = 49,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_START_ADDR      = 12,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_STOP_ADDR       = 12,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_TRIG_SRC        = 2,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_CNST_RUN        = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_PRE_CONF        = 5,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_SYNC_RDY        = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_BSUM            = 19,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_BSUM_LEN_SEL    = 3,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_BSUM_VALID      = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_LOCAL_COINC     = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_PARTIAL_WFM     = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_CONTINUED_WFM   = 1,
  L_WIDTH_MDOM_SCDB_HDR_BUNDLE_CHANNEL_IDX     = 5;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_EVT_LTC         = 0,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_START_ADDR      = 49,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_STOP_ADDR       = 61,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_TRIG_SRC        = 73,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_CNST_RUN        = 75,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_PRE_CONF        = 76,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_SYNC_RDY        = 81,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_BSUM            = 82,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_LEN_SEL    = 101,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_VALID      = 104,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_LOCAL_COINC     = 105,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_PARTIAL_WFM     = 106,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_CONTINUED_WFM   = 107,
  L_START_POS_MDOM_SCDB_HDR_BUNDLE_CHANNEL_IDX     = 108;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_EVT_LTC         = 48,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_START_ADDR      = 60,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_STOP_ADDR       = 72,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_TRIG_SRC        = 74,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_CNST_RUN        = 75,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_PRE_CONF        = 80,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_SYNC_RDY        = 81,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_BSUM            = 100,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_LEN_SEL    = 103,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_BSUM_VALID      = 104,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_LOCAL_COINC     = 105,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_PARTIAL_WFM     = 106,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_CONTINUED_WFM   = 107,
  L_STOP_POS_MDOM_SCDB_HDR_BUNDLE_CHANNEL_IDX     = 112;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_SCDB_HDR_BUNDLE_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_SCDB_HDR_BUNDLE = 113;
