# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_SECONDARY_BUFFER/MDOM_SECONDARY_BUFFER.xci
# IP: The module: 'MDOM_SECONDARY_BUFFER' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_SECONDARY_BUFFER/MDOM_SECONDARY_BUFFER_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MDOM_SECONDARY_BUFFER'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_SECONDARY_BUFFER/MDOM_SECONDARY_BUFFER.xci
# IP: The module: 'MDOM_SECONDARY_BUFFER' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_SECONDARY_BUFFER/MDOM_SECONDARY_BUFFER_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MDOM_SECONDARY_BUFFER'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
