// Widths
localparam
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_EVT_LTC         = 49,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_START_ADDR      = 10,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_STOP_ADDR       = 10,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_TRIG_SRC        = 2,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_CNST_RUN        = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_PRE_CONF        = 5,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_SYNC_RDY        = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_BSUM            = 19,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_BSUM_LEN_SEL    = 3,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_BSUM_VALID      = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_LOCAL_COINC     = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_PARTIAL_WFM     = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_CONTINUED_WFM   = 1;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_EVT_LTC         = 0,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_START_ADDR      = 49,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_STOP_ADDR       = 59,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_TRIG_SRC        = 69,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_CNST_RUN        = 71,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_PRE_CONF        = 72,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_SYNC_RDY        = 77,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM            = 78,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_LEN_SEL    = 97,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_VALID      = 100,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_LOCAL_COINC     = 101,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_PARTIAL_WFM     = 102,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_CONTINUED_WFM   = 103;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_EVT_LTC         = 48,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_START_ADDR      = 58,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_STOP_ADDR       = 68,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_TRIG_SRC        = 70,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_CNST_RUN        = 71,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_PRE_CONF        = 76,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_SYNC_RDY        = 77,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM            = 96,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_LEN_SEL    = 99,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_VALID      = 100,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_LOCAL_COINC     = 101,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_PARTIAL_WFM     = 102,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_CONTINUED_WFM   = 103;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_WVB_HDR_BUNDLE_4 = 104;
