// Widths
localparam
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_EVT_LTC         = 49,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_START_ADDR      = 9,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_STOP_ADDR       = 9,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_TRIG_SRC        = 2,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_CNST_RUN        = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_PRE_CONF        = 5,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_SYNC_RDY        = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_BSUM            = 19,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_BSUM_LEN_SEL    = 3,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_BSUM_VALID      = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_LOCAL_COINC     = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_PARTIAL_WFM     = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_CONTINUED_WFM   = 1;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_EVT_LTC         = 0,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_START_ADDR      = 49,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_STOP_ADDR       = 58,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_TRIG_SRC        = 67,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_CNST_RUN        = 69,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_PRE_CONF        = 70,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_SYNC_RDY        = 75,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM            = 76,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_LEN_SEL    = 95,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_VALID      = 98,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_LOCAL_COINC     = 99,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_PARTIAL_WFM     = 100,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_4_CONTINUED_WFM   = 101;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_EVT_LTC         = 48,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_START_ADDR      = 57,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_STOP_ADDR       = 66,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_TRIG_SRC        = 68,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_CNST_RUN        = 69,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_PRE_CONF        = 74,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_SYNC_RDY        = 75,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM            = 94,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_LEN_SEL    = 97,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_BSUM_VALID      = 98,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_LOCAL_COINC     = 99,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_PARTIAL_WFM     = 100,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_4_CONTINUED_WFM   = 101;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_WVB_HDR_BUNDLE_4_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_WVB_HDR_BUNDLE_4 = 102;
