# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/constrs/clocks.xdc

# XDC: C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/constrs/io.xdc

# IP: ip/MDOM_CHANNEL_HDR_FIFO/MDOM_CHANNEL_HDR_FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MDOM_CHANNEL_HDR_FIFO || ORIG_REF_NAME==MDOM_CHANNEL_HDR_FIFO} -quiet] -quiet
