# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7s100fgga676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.cache/wt [current_project]
set_property parent.project_path C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/inc/trigger_src
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_trig_bundle
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_wvb_conf_bundle
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_wvb_hdr_bundle_0
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_wvb_hdr_bundle_1
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_wvb_hdr_bundle_2
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_bsum_bundle
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/rev_num
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_wvb_hdr_bundle_3
  C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/hdl/bundles/mDOM_wvb_hdr_bundle_4
} [current_fileset]
read_ip -quiet c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER.xci
set_property used_in_implementation false [get_files -all c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1 -new_name MDOM_CHANNEL_BUFFER -ip [get_ips MDOM_CHANNEL_BUFFER]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top MDOM_CHANNEL_BUFFER -part xc7s100fgga676-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix MDOM_CHANNEL_BUFFER_ MDOM_CHANNEL_BUFFER.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MDOM_CHANNEL_BUFFER_stub.v
 lappend ipCachedFiles MDOM_CHANNEL_BUFFER_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MDOM_CHANNEL_BUFFER_stub.vhdl
 lappend ipCachedFiles MDOM_CHANNEL_BUFFER_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MDOM_CHANNEL_BUFFER_sim_netlist.v
 lappend ipCachedFiles MDOM_CHANNEL_BUFFER_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MDOM_CHANNEL_BUFFER_sim_netlist.vhdl
 lappend ipCachedFiles MDOM_CHANNEL_BUFFER_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp MDOM_CHANNEL_BUFFER.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips MDOM_CHANNEL_BUFFER]
}

rename_ref -prefix_all MDOM_CHANNEL_BUFFER_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MDOM_CHANNEL_BUFFER.dcp
create_report "MDOM_CHANNEL_BUFFER_synth_1_synth_report_utilization_0" "report_utilization -file MDOM_CHANNEL_BUFFER_utilization_synth.rpt -pb MDOM_CHANNEL_BUFFER_utilization_synth.pb"

if { [catch {
  file copy -force C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1/MDOM_CHANNEL_BUFFER.dcp c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1/MDOM_CHANNEL_BUFFER.dcp c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1/MDOM_CHANNEL_BUFFER_stub.v c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1/MDOM_CHANNEL_BUFFER_stub.vhdl c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1/MDOM_CHANNEL_BUFFER_sim_netlist.v c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.runs/MDOM_CHANNEL_BUFFER_synth_1/MDOM_CHANNEL_BUFFER_sim_netlist.vhdl c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.ip_user_files/ip/MDOM_CHANNEL_BUFFER]} {
  catch { 
    file copy -force c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_stub.v C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.ip_user_files/ip/MDOM_CHANNEL_BUFFER
  }
}

if {[file isdir C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.ip_user_files/ip/MDOM_CHANNEL_BUFFER]} {
  catch { 
    file copy -force c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/MDOM_CHANNEL_BUFFER/MDOM_CHANNEL_BUFFER_stub.vhdl C:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.ip_user_files/ip/MDOM_CHANNEL_BUFFER
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
