# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/OVERFLOW_FIFO_1/OVERFLOW_FIFO.xci
# IP: The module: 'OVERFLOW_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/OVERFLOW_FIFO_1/OVERFLOW_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'OVERFLOW_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/OVERFLOW_FIFO_1/OVERFLOW_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OVERFLOW_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/OVERFLOW_FIFO_1/OVERFLOW_FIFO.xci
# IP: The module: 'OVERFLOW_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/OVERFLOW_FIFO_1/OVERFLOW_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'OVERFLOW_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/i3devmachine/mdom/updates/mdommb_rev1_fw/mDOM_mb_rev1.srcs/sources_1/ip/OVERFLOW_FIFO_1/OVERFLOW_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OVERFLOW_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
